metadata:
  name: postgres 
  namespace: todo

  replicaCount: 1

image:
  repository: postgres:latest
  pullPolicy: IfNotPresent

container:
  name: postgres
  port: 5432
  
secret:
  metadata:
    name: postgres-secret
  type: Opaque
  data:
    dbuser: cG9zdGdyZXM=
    dbpassword: MTIzNDU2

service:
  metadata:
    name: postgres-service
  type: NodePort
  name: http
  port: 5432
  protocol: TCP
  targetPort: 5432